electron/mksnapshot

download-mksnapshot.js, package.json
Uses electron-download to download mksnapshot removing code duplication anding support for progress bar output and shasum validation.
Refs https://github.com/electron-userland/electron-download/pull/42
=> Use electron-download to download mksnapshot

download-mksnapshot.js
The file for arm64 is named "mksnapshot-vX.Y.Z-linux-arm64-x64.zip", and currently this script tries to download "mksnapshot-vX.Y.Z-linux-arm64.zip" and fails on arm64. The same applies for armv7l.
=> fix: Allow downloading of x64 binary for arm64 snapshots

.circleci/config.yml, README.md, download-mksnapshot.js, mksnapshot.js, package-lock.json, package.json
This PR updates this module to work correctly with our arm*-x64 zips which are used to generate snapshots for arm hardware from an Intel x64 machine.  This is the only way to generate snapshots for ARM hardware.  
Additionally, this resolves #23 as much as we can.  If someone attempts to install this module on linux-armv7l, linux-arm64, or win32-arm64 an error message will be printed directing the user to download the x64 cross arch version of mksnapshot which can be used on an x64 machine to generate snapshots for those platforms.
=>  chore: update mksnapshot to work with arm*-x64 zips

README.md, download-mksnapshot.js, package-lock.json, package.json
This PR updates this module to the latest version of @electron/get which supports the ELECTRON_CUSTOM_VERSION environment variable.  This will allow users to override which version of mksnapshot gets downloaded.
Resolves: #29.
=> fix: Allow downloading of custom versions of mksnapshots

README.md, download-mksnapshot.js
mksnapshot for macOS arm64 is available as an x64 executable that generates arm64 compatible snapshots.  This PR changes electron-mksnapshot to download that version of mksnapshot because it can run on arm64 macs via rosetta.
Fixes #35
=> fix: download on arm64 macs

README.md, mksnapshot.js, package.json, test/mksnapshot-test.js
mksnapshot for macOS arm64 (Apple Silicon) uses a different file structure than other OSes/arches.  This PR updates mksnapshot to work properly when generating snapshots for macOS arm64.
Resolves #37, but #37 is also dependent on electron/electron#29338 being included in new Electron releases.
=>  chore: update mksnapshot to work with Apple Silicon

package-lock.json, package.json
As #56, 17.0.0 does not work with Electron 17.0.1, so this will publish a new version for use with Electron >= 17.0.1
Resolves #56
Alternatively 17.0.1 (or any version for that matter) can be used via:
```sh
ELECTRON_CUSTOM_VERSION=17.0.1 npm install
```
=> chore: 17.0.1

.github/workflows/release.yml
As in title. Before this is used, we'll need to generate an [automation token](https://github.blog/changelog/2020-10-02-npm-automation-tokens/) and set an `NPM_AUTH_TOKEN` secret appropriately.
=> build: add npm publish step to release workflow

README.md
Links are currently broken, this fixes 'em.
=> docs: fix npm badge links

.github/workflows/release.yml
Ensures that the correct mksnapshot binary is downloaded
=> ci: bump version before installing dependencies in release workflow

test/mksnapshot-test.js
Test was falling back to `x86_64` on Apple Silicon when run locally if `npm_config_arch` isn't set, which caused test failure.
=> test: fix detecting Apple Silicon

appveyor.yml
This stopped being run when the repo was cut over to using `main`. Also bumps the Node version to match the CircleCI config.
=> ci: fix AppVeyor config

script/update-version.js
Test is failing on `main` at the moment due to a rogue semicolon.
=> chore: remove semicolon to fix linting

.circleci/config.yml, .github/workflows/release.yml, download-mksnapshot.js, package-lock.json, package.json, script/publish.js
This repo needs to be switched over to CFA for releases. This PR is an attempt to get us there.
To safely transition, this PR only creates draft GH releases, so a follow-up PR should remove the draft flag once everything has ben confirmed to work as expected.
This PR makes several changes to how this repo works for releases:
* The version in `package.json` in `main` and for GH releases will always be `0.0.0-development`, the same as repos covered by semantic releases
* `download-mksnapshot.js` will fall back to latest stable if the version is `0.0.0-development`, so that tests can run
* `.github/workflows/release.yml` will handle the git tag and GH release
* `.circleci/config.yml` will handle the CFA release, triggering on new git tags
=> build: do CFA releases

.circleci/config.yml
Unfortunately [the release job did not trigger](https://app.circleci.com/pipelines/github/electron/mksnapshot/199) for the tag because the jobs it depends on were not marked as being able to run on tags.
Refs https://circleci.com/docs/workflows/#executing-workflows-for-a-git-tag
=> build: run all jobs on tags

script/publish.js
CFA releases are almost complete but `npm publish` is failing and it's not clear why, so log output in the case of a failure.
=> chore: add debugging output to publish script

download-mksnapshot.js, package-lock.json, package.json
This was already using copied code from `@electron/fiddle-core`, so for better maintainability just use `@electron/fiddle-core` directly now that it has the `ignoreCache` option.
=> chore: use @electron/fiddle-core to get latest stable version

.circleci/config.yml
Same change as https://github.com/electron/chromedriver/pull/124
=> build: bump CFA publish step timeout

.circleci/config.yml
We aren't getting clean runs on the M1 runners for Electron <= 26, so roll back to x86 runners for now and we'll revert this once 29 is released.
=> ci: roll back to x86 macOS executors

.circleci/config.yml
Follow-up to #105 which said we'd revert this once E29 released but I forgot to do it. 🙃
=> ci: use macos executor from orb

.github/workflows/publish-npm.yml, .github/workflows/release.yml, .releaserc.json, package-lock.json, package.json, script/publish.js
Partially reverts #120. I had a brain fart and forgot this repo can't use standard `semantic-release` since it does arbitrary release versions to have a 1:1 with Electron versions.
Restores some of the previous code (e.g. `scripts/publish.js`) and unwraps `continuousauth/action` to get the npm token we need to publish. Also uses the GitHub credentials from CFA so now releases should be published by the `continuousauth` app.
=> ci: fix CFA publishing on GHA

.github/workflows/release.yml
Third time's the charm, forgot the whole GitHub Actions won't trigger another workflow caveat.
=> ci: use GitHub app to tag new release

.github/workflows/publish-npm.yml
The GH token acquired is only good for 1 hour, and if a maintainer provides a CFA token after that time we end up with the npm publish going through but none of the follow-up steps on GitHub (creating the release).
=> ci: timeout release job after 1 hour
